### ISSUE TITLE
confused on how to use.

### ISSUE THREAD

**Issue by toothless132** [Moorad/youtubeDownloader#24]
I have looked everywhere and cloned it but I can't find anywhere I can either download it or use it. I am new to Github and that's not helping but is there something I missed?

**Comment by Moorad** [comment]
hmm, I'm not sure where your problem lies so I will list the steps to setup this project and if you run into any problem please tell me :')

1. Install Node.js on your computer. You can do that by going to https://nodejs.org/en/ and downloading the LTS or the Current version (Preferably LTS but either version should work)
2. Download the code from this respiratory by going to https://github.com/Moorad/youtubeDownloader and clicking the green "Clone or download" button then clicking on "download ZIP"
3. Extract the ZIP file you just downloaded by right clicking on the zip file > Extract All > Extract (Or extract it using WinRAR if you know how to). Then move the extracted folder to whatever directory you want.
4. Open Command Prompt and navigate to wherever directory you moved the files to then navigate to the Server folder (if you don't know how to navigate using the command prompt, visit this tutorial maybe? https://riptutorial.com/cmd/example/8646/navigating-in-cmd)
5. Once you navigated to the server folder run `npm install` which should download all the dependencies for the project
6. Run `node index.js` which will run index.js and if everything worked correctly you should see `Server Works !!! At port 4000`
7. In your File explorer right click index.html > Open with and choose whatever browser you like (preferably Chrome)
8. And that is it, the page should open and work just fine.

**Comment by toothless132** [comment]
ahh ok. so I don't have Node.js yet (i will though). also, why is it that the Node.js page just comes up with a #blacklivesmatter page.

**Comment by Moorad** [comment]
Oh, I just looked at it and indeed it did change from when I first looked at it this morning. You can still access the download from https://nodejs.org/en/download/

**Comment by Moorad** [comment]
Any updates?

**Comment by Moorad** [comment]
I will close this issue for now but if you are still having problems you can reply here and I will reopen it back again.
