### ISSUE TITLE
TypeError: Cannot read property 'player_response' of undefined

### ISSUE THREAD

**Issue by gurusabarish** [Moorad/youtubeDownloader#27]
I just paste this link https://www.youtube.com/watch?v=ryD8BqVexJI&list=RDryD8BqVexJI&start_radio=1 and press the convert button with mp3. But, its **running more then 10 minutes** and i got the **TypeError in my windows terminal** like that image.

Could you help me to find the error?

![error](https://user-images.githubusercontent.com/52481812/86891895-5b804280-c0b4-11ea-83c5-7b5666882aef.PNG)

**Comment by Moorad** [comment]
hmm, did you modify the code? I tried converting the URL with a fresh clone of the code and it works as I expected for me. If you have modified it can you show me?

**Comment by gurusabarish** [comment]
Thanks for your reply @Moorad 
But, I didn't modify the code. I guess the problem is runing the server at port 4000. I just run the index file in my local pc server. You can view that in search box of the above image.

Could you tell me "How to run the npm server at port 4000 after the **node index.js** comment" ?

**Comment by Moorad** [comment]
I don't think the issue is related to the port. Running `node index.js` should run the server on port 4000 automatically (because it's hardcoded in the code. You can look at line 5 in index.js.) and the index.html is already setup so that it redirects you to `localhost:4000` (`:4000` means port 4000).

If the port was indeed in use by another application or service you should get an error similar to
![image](https://user-images.githubusercontent.com/34781684/86928857-cb86db00-c13d-11ea-8779-625c5fc68417.png)

The problem is most likely related to (This is on lines 18-22)
```
await ytdl.getBasicInfo(url, {
	format: 'mp4'
}, (err, info) => {
	title = info.player_response.videoDetails.title.replace(/[^\x00-\x7F]/g, "");
});
```

Currently any errors that ytdl throws are ignored. Try replacing the above with
```
await ytdl.getBasicInfo(url, {
	format: 'mp4'
}, (err, info) => {
	if (err) throw err;
	title = info.player_response.videoDetails.title.replace(/[^\x00-\x7F]/g, "");
});
```

This should output any errors that occur during the execution of `ytdl.getBasicInfo()`. Try that and show me if any new errors appear

**Comment by gurusabarish** [comment]
Now I got the error in **getBasicInfo**. 

![Capture](https://user-images.githubusercontent.com/52481812/86934703-dc5d2f80-c0f0-11ea-93fe-fe29e6ea2daf.PNG)

**Comment by Moorad** [comment]
Hmm what version of ytdl-core do you have? You can find the version in package.json in `dependencies`

**Comment by gurusabarish** [comment]
I have the **ytdl-core: ^2.0.0**. This is my Package file.
![Capture1](https://user-images.githubusercontent.com/52481812/86938635-7f17ad00-c0f5-11ea-99b4-8942ab625c6c.PNG)

**Comment by Moorad** [comment]
Ok according to this https://github.com/fent/node-ytdl-core/issues/585#issuecomment-636081145 the latest version fixes the JSON problem. I also have version 2.0.0 but I don't have the same problem for some reason.

Running
```
npm i ytdl-core@latest
```
in the Server folder should fix the problem

**Comment by Moorad** [comment]
let me know if you still have the problem

**Comment by gurusabarish** [comment]
Thanks for your help to fix. 
Now, Its works super cool :)
